name: Vue check
on: push

jobs:
  vue-tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: keita-hino/vue-tsc-action@main

  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: UnicornGlobal/spellcheck-github-actions@master